baseURL = 'https://isabelcosta.github.io/'
languageCode = 'en-us'
theme = 'etch'
title = 'Isabel Costa'

[params]
  description = "Isabel Costa is a software engineer from Portugal, who really likes Open Source, Freecell, Clash of Clans, and much more."
  copyright = "Copyright © 2022 Isabel Costa"
  dark = "auto"
  highlight = true
  favicon = "/images/favicon.ico"

  [params.socialMedia]
    linkedin = "https://www.linkedin.com/in/isabelcmdcosta"
    github = "https://github.com/isabelcosta"
    devto = "https://dev.to/isabelcmdcosta"
    medium = "https://medium.com/@isabelcmdcosta"
    twitter = "https://twitter.com/isabelcmdcosta"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about/"
    weight = 20
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/posts/"
    weight = 20
  [[menu.main]]
    identifier = "talks"
    name = "talks"
    title = "talks"
    url = "/talks/"
    weight = 20
